# Generated by Django 6.1.1 on 2026-09-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
